---
- name: Download docker images
  hosts: all
  tasks:
    - name: Image downloading
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
       - nginx
       - tomee
       - httpd
       - ghost

