---
- name: Create an ubuntu container and mount /data as a volume
  hosts: all
  tasks:
    - name: Create ubuntu container
      docker_container:
        name: u1
        image: ubuntu
        interactive: yes
        tty: yes
        volumes:
          - /data
...
