---
- name: Implementing docker compose from ansible
  hosts: all
  tasks:
    - name: Create a mysql contianer
      docker_container:
        name: mydb
        image: mysql:5 
        env:
          MYSQL_ROOT_PASSWORD: intelliqit

    - name: Create a wordpress container
      docker_container:
        name: mywordpress
        image: wordpress
        ports:
          - 8888:80
        links:
          - mydb:mysql
...
